In [3]:
import pandas as pd
students =pd.DataFrame({
    "student_id":[101,102,103,104,105,106,107,108],
    "name":["Ali","wahab","zoya","waleed","rayan","duad","eman","hassan"],
    "age":[20,21,23,23,21,20,19,20],
    "deparments":["se","cs","it","math","se","cs","it","math"],
    "marks":[89,67,98,55,77,71,89,49],
    "attendence":[77,88,80,90,85,75,83,91]})
print(students)

   student_id    name  age deparments  marks  attendence
0         101     Ali   20         se     89          77
1         102   wahab   21         cs     67          88
2         103    zoya   23         it     98          80
3         104  waleed   23       math     55          90
4         105   rayan   21         se     77          85
5         106    duad   20         cs     71          75
6         107    eman   19         it     89          83
7         108  hassan   20       math     49          91

In [4]:
#print top two rows
students.head(2)

   student_id   name  age deparments  marks  attendence
0         101    Ali   20         se     89          77
1         102  wahab   21         cs     67          88

In [6]:
students.tail(1)

   student_id    name  age deparments  marks  attendence
7         108  hassan   20       math     49          91

In [7]:
students[["name","marks"]]

     name  marks
0     Ali     89
1   wahab     67
2    zoya     98
3  waleed     55
4   rayan     77
5    duad     71
6    eman     89
7  hassan     49

In [8]:
students[students["marks"]>80]

   student_id  name  age deparments  marks  attendence
0         101   Ali   20         se     89          77
2         103  zoya   23         it     98          80
6         107  eman   19         it     89          83

In [10]:

students.sort_values(by="marks", ascending=False)

   student_id    name  age deparments  marks  attendence
2         103    zoya   23         it     98          80
0         101     Ali   20         se     89          77
6         107    eman   19         it     89          83
4         105   rayan   21         se     77          85
5         106    duad   20         cs     71          75
1         102   wahab   21         cs     67          88
3         104  waleed   23       math     55          90
7         108  hassan   20       math     49          91

In [11]:
students["marks"].mean()

np.float64(74.375)

In [12]:
students["marks"].agg(["min","max"])

min    49
max    98
Name: marks, dtype: int64

In [20]:
def grade(marks):
    if marks >= 90:          
        return "A+"
    elif marks >= 80:        
        return "A"
    elif marks >= 70:        
        return "B"
    elif marks >= 60:        
        return "C"
    elif marks >= 50:        
        return "D"
    else:             
        return "F"

students["grade"] = students["marks"].apply(grade)
print(students)

   student_id    name  age deparments  marks  attendence grade
0         101     Ali   20         se     89          77     A
1         102   wahab   21         cs     67          88     C
2         103    zoya   23         it     98          80    A+
3         104  waleed   23       math     55          90     D
4         105   rayan   21         se     77          85     B
5         106    duad   20         cs     71          75     B
6         107    eman   19         it     89          83     A
7         108  hassan   20       math     49          91     F

In [24]:
students["pass"]=students["marks"].apply(
    lambda x:"pass" if x>=50 else "fail")
print(students)

   student_id    name  age deparments  marks  attendence grade  pass
0         101     Ali   20         se     89          77     A  pass
1         102   wahab   21         cs     67          88     C  pass
2         103    zoya   23         it     98          80    A+  pass
3         104  waleed   23       math     55          90     D  pass
4         105   rayan   21         se     77          85     B  pass
5         106    duad   20         cs     71          75     B  pass
6         107    eman   19         it     89          83     A  pass
7         108  hassan   20       math     49          91     F  fail

In [30]:
students.loc[students["deparments"]=="cs","marks"]+=5

In [32]:
students.iloc[0:4]

   student_id    name  age deparments  marks  attendence grade  pass
0         101     Ali   20         se     89          77     A  pass
1         102   wahab   21         cs     72          88     C  pass
2         103    zoya   23         it     98          80    A+  pass
3         104  waleed   23       math     55          90     D  pass

In [34]:
students.loc[(students["deparments"].isin(["cs" , "it"]))&(students["grade"]=="A+")]

   student_id  name  age deparments  marks  attendence grade  pass
2         103  zoya   23         it     98          80    A+  pass

In [36]:
students.rename(
    columns={"mark":"exam_marks"},inplace=True)

In [42]:
students[students["name"].str.startswith("A")]

   student_id name  age deparments  marks  attendence grade  pass
0         101  Ali   20         se     89          77     A  pass

In [43]:
students[students["name"].str.endswith("d")]

   student_id    name  age deparments  marks  attendence grade  pass
3         104  waleed   23       math     55          90     D  pass
5         106    duad   20         cs     76          75     B  pass

In [44]:
students[students["attendence"]>students["attendence"].mean()]

   student_id    name  age deparments  marks  attendence grade  pass
1         102   wahab   21         cs     72          88     C  pass
3         104  waleed   23       math     55          90     D  pass
4         105   rayan   21         se     77          85     B  pass
7         108  hassan   20       math     49          91     F  fail

In [47]:
students.nlargest(3,"marks")

   student_id  name  age deparments  marks  attendence grade  pass
2         103  zoya   23         it     98          80    A+  pass
0         101   Ali   20         se     89          77     A  pass
6         107  eman   19         it     89          83     A  pass

In [48]:
students.nsmallest(2,"marks")

   student_id    name  age deparments  marks  attendence grade  pass
7         108  hassan   20       math     49          91     F  fail
3         104  waleed   23       math     55          90     D  pass

In [50]:
students.groupby("deparments")["marks"].mean()

deparments
cs      74.0
it      93.5
math    52.0
se      83.0
Name: marks, dtype: float64

In [52]:
students.groupby("deparments")["marks"].max()

deparments
cs      76
it      98
math    55
se      89
Name: marks, dtype: int64

In [53]:
students.groupby("deparments")["marks"].min()

deparments
cs      72
it      89
math    49
se      77
Name: marks, dtype: int64

In [54]:
students.groupby("deparments")["student_id"].count()

deparments
cs      2
it      2
math    2
se      2
Name: student_id, dtype: int64

In [56]:
students[students["marks"]==students["marks"].max()]

   student_id  name  age deparments  marks  attendence grade  pass
2         103  zoya   23         it     98          80    A+  pass

In [57]:
students[students["attendence"]==students["attendence"].min()]

   student_id  name  age deparments  marks  attendence grade  pass
5         106  duad   20         cs     76          75     B  pass

In [59]:
students["deparments"]=students["deparments"].replace("it","information technology")

In [60]:
students.set_index("student_id",inplace=True)

In [61]:
print(students)

              name  age              deparments  marks  attendence grade  pass
student_id
101            Ali   20                      se     89          77     A  pass
102          wahab   21                      cs     72          88     C  pass
103           zoya   23  information technology     98          80    A+  pass
104         waleed   23                    math     55          90     D  pass
105          rayan   21                      se     77          85     B  pass
106           duad   20                      cs     76          75     B  pass
107           eman   19  information technology     89          83     A  pass
108         hassan   20                    math     49          91     F  fail

In [63]:

students["phone"] = [
    "0455667788655", None, "4455678864", None, 
    "5674322567", None, "3334563226", None  
]
print(students)

              name  age              deparments  marks  attendence grade  \
student_id
101            Ali   20                      se     89          77     A
102          wahab   21                      cs     72          88     C
103           zoya   23  information technology     98          80    A+
104         waleed   23                    math     55          90     D
105          rayan   21                      se     77          85     B
106           duad   20                      cs     76          75     B
107           eman   19  information technology     89          83     A
108         hassan   20                    math     49          91     F

            pass          phone
student_id
101         pass  0455667788655
102         pass           None
103         pass     4455678864
104         pass           None
105         pass     5674322567
106         pass           None
107         pass     3334563226
108         fail           None

In [68]:
students.isnull().sum()

name          0
age           0
deparments    0
marks         0
attendence    0
grade         0
pass          0
phone         4
dtype: int64

In [69]:
students["phone"]=students["phone"].fillna("not available")

In [74]:

students.loc[students.groupby("deparments")["marks"].idxmax()]

,name,age,deparments,marks,attendence,grade,pass,phone
student_id,,,,,,,,
106,duad,20,cs,76,75,B,pass,not available
103,zoya,23,information technology,98,80,A+,pass,4455678864
104,waleed,23,math,55,90,D,pass,not available
101,Ali,20,se,89,77,A,pass,0455667788655

In [77]:

students.to_csv("students_report.csv", index=False)